version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db_postgres
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - pg_volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_INITDB_ARGS="-A md5"

  service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: movies_django
    depends_on:
      - db
    volumes:
      - static_volume:/opt/django_api/static/
      - media_volume:/opt/django_api/media/

    command: >
      bash -c "python manage.py collectstatic --noinput && \
      python manage.py makemigrations && \
      python manage.py migrate && \
      python init_superuser.py && \
      uwsgi --strict --ini uwsgi.ini"
  #      init_superuser ?

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/opt/django_api/static/
      - media_volume:/opt/django_api/media/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  media_volume:
  static_volume:
  pg_volume: