# Generated by Django 4.2.6 on 2023-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0003_alter_filmwork_file_path_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
